platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: vsphere-patch-hosts-pipeline

run:
  path: ./vsphere-patch-hosts-pipeline/tasks/patch/task.sh
