vcenter_url:  #IP Address or DNS for vCenter
vcenter_username:  #username for vCenter
vcenter_password:  #password for vCenter
vcenter_insecure:  #true or false value indicating whether or not to ignore the SSL Cert
